### ISSUE TITLE
@debug causes stack overflow in serialize()

### ISSUE THREAD

**Issue by rened** [toivoh/Debug.jl#71]
First, Toivo, thanks a ton for this awesome package, it rescued me not only once!

While parallelizing my code, where anonymous functions are being passed to `pmap` and thus serialized, I found the following (reduced example):

```jl
using Debug
@debug begin
    serialize(IOBuffer(),()->1)
end
```
gives a `stack overflow` error, which occurs in
```jl
 in handle_deserialize at serialize.jl:351
 in deserialize at serialize.jl:412
 in handle_deserialize at serialize.jl:351
 in deserialize at serialize.jl:405
 in handle_deserialize at serialize.jl:351
 in deserialize at serialize.jl:565
 in deserialize at serialize.jl:520
```
When I remove the `@debug` everything works as expected.
I can understand that of course `Debug` heavily instruments the code to make its magic happen, but it would be very, very handy if serialization and thus parallel processing would still work.
Thanks!
(on OSX, Julia 0.3.8, Debug 0.1.3)

**Comment by toivoh** [comment]
Thanks, @rened!
It seems that the trouble here is that when you wrap your example code in `@debug`, also the function `()->1` gets instrumented. I guess that the stack overflow is caused by the fact that the instrumented code contains references to the decorated AST, which is a data structure with loops.

I think I saw some recent issue about making the serializer handle objects with loops, but I'm not sure about the state of that.

Anyway, I guess that if you are going to send those closures to other workers then you probably don't want to instrument them. Perhaps I can add a `@nodebug` macro that you can use to wrap code that you never want to instrument. Not sure how hard that would be...

**Comment by toivoh** [comment]
I think I have fixed this as best I can on the latest master. Now you can do

    using Debug
    @debug begin
        serialize(IOBuffer(), @notrap ()->1)
    end

and it seems to work. `@notrap` tells Debug not to instrument the wrapped code. It also works for me with

    using Debug
    begin
        serialize(IOBuffer(), @notrap ()->1)
    end

so you don't have to debug your code to use this :)
Please try it out and tell me if it helps!

**Comment by rened** [comment]
Yes, fantastic, works like a charm! Thank you so much for the super fast fix!

**Comment by toivoh** [comment]
Your welcome! Glad to hear that it helps.
